export const UserActionsConstants = {
    CONNEXION: "Connexion",
    EXPORTATION_STATISTIQUES_PDF: "Exportation des données statistiques en PDF",
    EXPORTATION_STATISTIQUES_EXCEL: "Exportation des données statistiques en EXCEL",
    AJOUT_SECTEUR: "Ajout d'un secteur",
    MODIFICATION_SECTEUR: "Modification d'un secteur",
    SUPPRESSION_SECTEUR: "Suppresion d'un secteur",
    ERREUR_AJOUT_SECTEUR: "Erreur lors de l'ajout d'un secteur",
    ERREUR_MODIFICATION_SECTEUR: "Erreur lors de la modification d'un secteur",
    ERREUR_SUPPRESSION_SECTEUR: "Erreur lors de la suppression d'un secteur",
    AJOUT_NIVEAU: "Ajout d'un niveau",
    MODIFICATION_NIVEAU: "Modification d'un niveau",
    SUPPRESSION_NIVEAU: "Suppression d'un niveau",
    ERREUR_AJOUT_NIVEAU: "Erreur lors de l'ajout d'un niveau",
    ERREUR_MODIFICATION_NIVEAU: "Erreur lors de la modification d'un niveau",
    ERREUR_SUPPRESSION_NIVEAU: "Erreur lors de la suppression d'un niveau",
    AJOUT_CATEGORIE: "Ajout d'une catégorie",
    MODIFICATION_CATEGORIE: "Modification d'une catégorie",
    SUPPRESSION_CATEGORIE: "Suppression d'une catégorie",
    ERREUR_AJOUT_CATEGORIE: "Erreur lors de l'ajout d'une catégorie",
    ERREUR_MODIFICATION_CATEGORIE: "Erreur lors de la modification d'une catégorie",
    ERREUR_SUPPRESSION_CATEGORIE: "Erreur lors de la suppression d'une catégorie",
    AJOUT_PILIER: "Ajout d'un pilier",
    AJOUT_PILIER_MOTCLE: "Ajout des mot-clés d'un pilier",
    MODIFICATION_PILIER: "Modification d'un pilier",
    SUPPRESSION_PILIER: "Suppression d'un pilier",
    SUPPRESSION_PILIER_MOTCLE: "Suppression des mot-clés d'un pilier",
    ERREUR_AJOUT_PILIER: "Erreur lors de l'ajout d'un pilier",
    ERREUR_AJOUT_PILIER_MOTCLE: "Erreur lors de l'ajout des mot-clés d'un pilier",
    ERREUR_MODIFICATION_PILIER: "Erreur lors de la modification d'un pilier",
    ERREUR_SUPPRESSION_PILIER: "Erreur lors de la suppression d'un pilier",
    ERREUR_SUPPRESSION_PILIER_MOTCLE: "Erreur lors de la suppression des mot-clés d'un pilier",
    AJOUT_DEFI: "Ajout d'un défi",
    MODIFICATION_DEFI: "Modification d'un défi",
    MODIFICATION_DEFI_FICHE: "Remplacement de la fiche d'un défi",
    SUPPRESSION_DEFI: "Suppression d'un défi",
    ERREUR_AJOUT_DEFI: "Erreur lors de l'ajout d'un défi",
    ERREUR_MODIFICATION_DEFI: "Erreur lors de la modification d'un défi",
    ERREUR_MODIFICATION_DEFI_FICHE: "Erreur lors du remplacement de la fiche d'un défi",
    ERREUR_SUPPRESSION_DEFI: "Erreur lors de la suppression d'un défi",
    AJOUT_QUESTION: "Ajout d'une question",
    MODIFICATION_QUESTION: "Modification d'une question",
    SUPPRESSION_QUESTION: "Suppression d'une question",
    ERREUR_AJOUT_QUESTION: "Erreur lors de l'ajout d'une question",
    ERREUR_MODIFICATION_QUESTION: "Erreur lors de la modification d'une question",
    ERREUR_SUPPRESSION_QUESTION: "Erreur lors de la suppression d'une question",
}